set client_min_messages to warning;

-- DANGER: this is NOT how to do it in the real world.
-- `drop schema` INSTANTLY ERASES EVERYTHING.
drop schema "public" cascade;

create schema "public";

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar,
  "password" varchar,
  "created_at" timestamp
);

CREATE TABLE "teams" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "name" varchar,
  "created_at" timestamp
);

CREATE TABLE "players" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_id" integer,
  "name" varchar,
  "country" varchar,
  "position" varchar,
  "number" integer
);

CREATE TABLE "matches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "home_team_id" integer,
  "away_team_id" integer,
  "home_score" integer,
  "away_score" integer,
  "match_date" timestamp,
  "home_scorers" varchar,
  "away_scorers" varchar,
  "location" varchar,
  "home_team_possession" integer,
  "away_team_possession" integer,
  "home_team_shots" integer,
  "away_team_shots" integer,
  "home_team_shots_on_target" integer,
  "away_team_shots_on_target" integer,
  "home_team_fouls" integer,
  "away_team_fouls" integer,
  "home_team_corners" integer,
  "away_team_corners" integer,
  "home_team_offsides" integer,
  "away_team_offsides" integer
);

ALTER TABLE "teams" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "players" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("home_team_id") REFERENCES "teams" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("away_team_id") REFERENCES "teams" ("id");
