set client_min_messages to warning;

-- DANGER: this is NOT how to do it in the real world.
-- `drop schema` INSTANTLY ERASES EVERYTHING.
drop schema "public" cascade;

create schema "public";

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar
);

CREATE TABLE "teams" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "name" varchar
);

CREATE TABLE "players" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teamId" integer,
  "name" varchar,
  "country" varchar,
  "position" varchar,
  "number" varchar
);

CREATE TABLE "matches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "matchDate" varchar,
  "homeTeamName" varchar,
  "awayTeamName" varchar,
  "homeScore" varchar,
  "awayScore" varchar,
  "homeScorers" varchar,
  "awayScorers" varchar,
  "homeTeamPossession" varchar,
  "awayTeamPossession" varchar,
  "homeTeamShots" varchar,
  "awayTeamShots" varchar,
  "homeTeamShotsOnTarget" varchar,
  "awayTeamShotsOnTarget" varchar,
  "homeTeamFouls" varchar,
  "awayTeamFouls" varchar,
  "homeTeamCorners" varchar,
  "awayTeamCorners" varchar,
  "homeTeamOffsides" varchar,
  "awayTeamOffsides" varchar
);

ALTER TABLE "teams" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "players" ADD FOREIGN KEY ("teamId") REFERENCES "teams" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
